## Notebook used for testing the enviroment and ideas

In [ ]:
!pip install pybullet==2.5.5

%cd /usr/local/lib/python3.6/dist-packages
!git clone https://github.com/benelot/pybullet-gym.git
%cd pybullet-gym
!pip install -e .

  Using cached https://files.pythonhosted.org/packages/d4/6c/6b14ae6d1d8f10f16ea82c2c194394564b02c80b88b6e391470046968c7b/pybullet-2.5.5.tar.gz
  Created wheel for pybullet: filename=pybullet-2.5.5-cp36-cp36m-linux_x86_64.whl size=71821347 sha256=792d427a96b1160c99d3d623817e458b3040f4290730b1e247835517b6b0d524
  Stored in directory: /root/.cache/pip/wheels/1d/e4/cc/7b50d6689e1bc6ba07d2df04946a0eabc89deca7caed5f52d1
Successfully built pybullet
/usr/local/lib/python3.6/dist-packages
fatal: destination path 'pybullet-gym' already exists and is not an empty directory.
/usr/local/lib/python3.6/dist-packages/pybullet-gym
Obtaining file:///usr/local/lib/python3.6/dist-packages/pybullet-gym
  Running setup.py develop for pybulletgym


In [ ]:
import gym
import pybulletgym
from gym import logger as gymlogger
from gym.wrappers import Monitor
gymlogger.set_level(40) #error only

import numpy as np
from tqdm import trange
import glob
import io
import base64
from IPython.display import HTML

from IPython import display as ipythondisplay

### saving replay - useless

In [ ]:
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

<Display cmd_param=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1101'] cmd=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1101'] oserror=None return_code=None stdout="None" stderr="None" timeout_happened=False>

In [ ]:
def show_video(folder):
    mp4list = glob.glob(f'video/{folder}/*.mp4')
    if len(mp4list) > 0:
        mp4 = mp4list[0]
        video = io.open(mp4, 'r+b').read()
        encoded = base64.b64encode(video)
        ipythondisplay.display(HTML(data='''<video alt="test" autoplay 
                loop controls style="height: 200px;">
                <source src="data:video/mp4;base64,{0}" type="video/mp4" />
             </video>'''.format(encoded.decode('ascii'))))
    else: 
        print("Could not find video")
    

def wrap_env(env, folder):
    env = Monitor(env, f'./video/{folder}', force=True)
    return env

In [ ]:
env = wrap_env(gym.make("AntMuJoCoEnv-v0"), 'random')

current_dir=/Users/jakubgrodzicki/Library/Python/3.7/lib/python/site-packages/pybullet_envs/bullet
WalkerBase::__init__


In [ ]:
observation = env.reset()

for _ in trange(1000, position=0, leave=True):
    env.render()
    
    #your agent goes here
    action = env.action_space.sample() 
         
    observation, reward, done, info = env.step(action)
    if done: 
        break;
            
env.close()

options= 


100%|█████████▉| 999/1000 [00:23<00:00, 42.68it/s]


In [ ]:
show_video('random')

In [ ]:
import Network
n = Network.Network()
n.set_params(best)

In [ ]:
env = wrap_env(gym.make("AntMuJoCoEnv-v0"), 'test_100')
observation = env.reset()
observation = Network.to_tensor()

for _ in trange(2000, position=0, leave=True):
    env.render()
    
    #your agent goes here
    action = env.action_space.sample() 
         
    observation, reward, done, info = env.step(action)
    if done: 
        break;
            
env.close()

In [ ]:
env = wrap_env(gym.make("AntMuJoCoEnv-v0"), 'test_100')
actor = n

observation = env.reset()
observation = Network.to_tensor(observation.reshape(1, -1))
print(observation)

for _ in trange(2000, position=0, leave=True):
    action = actor(observation)
    action = Network.to_np(action)[0]

    if action[0] == np.nan:
        print(actor.get_params)
        print(action)

    observation, reward, done, info = env.step(action)
    observation = Network.to_tensor(observation.reshape(1, -1))

    if done:
        break

env.close()

WalkerBase::__init__
options= 


  0%|          | 0/2000 [00:00<?, ?it/s]

tensor([[ 0.7500,  0.0000,  0.0000,  0.0000,  1.0000, -0.0515, -0.0275,  0.0115,
          0.0683,  0.0551,  0.0589,  0.0657, -0.0933,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  

RuntimeError: Expected object of scalar type Float but got scalar type Double for argument #2 'mat1' in call to _th_addmm

### simulation

In [ ]:
env = gym.make("AntMuJoCoEnv-v0")
# env.render()  # put if want to render
observation = env.reset()

for _ in trange(2000, position=0, leave=True):
#     env.render()
    
    #your agent goes here
    action = env.action_space.sample()
    
    observation, reward, done, info = env.step(action)
    if done: 
        break;

env.close()

  4%|▍         | 80/2000 [00:00<00:02, 795.96it/s]

current_dir=/Users/jakubgrodzicki/Library/Python/3.7/lib/python/site-packages/pybullet_envs/bullet
WalkerBase::__init__
options= 


 50%|████▉     | 999/2000 [00:01<00:01, 738.72it/s]


In [ ]:
from Network import Network

In [ ]:
n = Network()

In [ ]:
n.get_params(), n.get_params().shape

(array([ 0.13997589,  0.11973168, -0.18422632, ...,  0.07988234,
         0.18694253,  0.01921986], dtype=float32),
 (1856,))

In [ ]:
import numpy as np
p = np.random.random(1856)

In [ ]:
%%time
n.set_params(p)

CPU times: user 1.04 ms, sys: 792 µs, total: 1.83 ms
Wall time: 1.28 ms


In [ ]:
%%time
n.get_params()

CPU times: user 441 µs, sys: 178 µs, total: 619 µs
Wall time: 522 µs


array([0.18542002, 0.34701434, 0.38515463, ..., 0.19055653, 0.57723075,
       0.4723062 ], dtype=float32)

### checking buffer

In [ ]:
env = gym.make("AntPyBulletEnv-v0")
observation = env.reset()
actions, rewards = [], []

for _ in trange(2000, position=0, leave=True):
    actions.append(env.action_space.sample())
    
    observation, reward, done, info = env.step(actions[-1])
    rewards.append(reward)
    if done: 
        break;

env.close()

  5%|▍         | 93/2000 [00:00<00:02, 880.37it/s]

WalkerBase::__init__


In [ ]:
observation.shape

(28,)

In [ ]:
done

True

In [ ]:
env.reset() == env.reset()

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
n.parameters

<bound method Module.parameters of Network(
  (layers): Sequential(
    (0): Linear(in_features=28, out_features=28, bias=True)
    (1): Tanh()
    (2): Linear(in_features=28, out_features=28, bias=True)
    (3): Tanh()
    (4): Linear(in_features=28, out_features=8, bias=True)
    (5): Tanh()
  )
)>